name: Release Go Binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build Linux binary
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o memmondiff-linux-amd64

      - name: Build Windows binary
        run: CGO_ENABLED=1 CC="zig cc -target x86_64-windows" GOOS=windows GOARCH=amd64 go build -o memmondiff-windows-amd64.exe

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            memmondiff-linux-amd64
            memmondiff-windows-amd64.exe
